FROM linux-emulation-base:25.04

# https://github.com/snes9xgit/snes9x/blob/master/.cirrus.yml
RUN apt update && apt -y install meson gettext libsdl2-dev libgtkmm-3.0-dev libgtk-3-dev libminizip-dev portaudio19-dev glslang-dev cmake
