on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  app:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # yuzu is not available anymore
        # suyu quality is down and development is not active anymore
        emulator: ["dolphin", "duckstation", "pcsx2", "rpcs3", "ryujinx", "snes9x"]
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      # first build container
      - run: ./run_container.sh ${{ matrix.emulator }} true
      # then build project
      - run: ./build_${{ matrix.emulator }}.sh
      - run: gh release upload --clobber build *AppImage
      - run: mv *AppImage ${{ matrix.emulator }}.AppImage
      - run: gh release upload --clobber latest ${{ matrix.emulator }}.AppImage

  keepalive-job:
    name: Keepalive Workflow
    if: ${{ always() }}
    needs: app
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      # https://github.com/marketplace/actions/workflow-keepalive
      - uses: liskin/gh-workflow-keepalive@v1
