on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  app:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # yuzu and ryujinx are not available anymore
        emulator: ["dolphin", "duckstation", "pcsx2", "rpcs3", "snes9x", "suyu"]
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      # first build container
      - run: ./run_container.sh ${{ matrix.emulator }} true
      # then build project
      - run: ./build_${{ matrix.emulator }}.sh || ./build_${{ matrix.emulator }}.sh
      - run: gh release upload --clobber build *AppImage
      - run: mv *AppImage ${{ matrix.emulator }}.AppImage
      - run: gh release upload --clobber latest ${{ matrix.emulator }}.AppImage

  keepalive-job:
    name: Keepalive Workflow
    if: ${{ always() }}
    needs: app
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: false
