on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches: [ "master" ]

jobs:
  app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emulator: ["dolphin", "yuzu", "pcsx2", "rpcs3"]
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: ./build_${{ matrix.emulator}}.sh
      - run: gh release upload --clobber build *AppImage
      - run: mv *AppImage ${{ matrix.emulator}}.AppImage
      - run: gh release upload --clobber latest ${{ matrix.emulator}}.AppImage
